import { useEffect, useMemo, useRef, useState } from 'react'
import { buildWeeklyGoals, loadBoardData, loadLockInState } from '../lib/lockIn'
import { calculateUserPoints, getStoredUserLevel } from '../lib/userLevel'

const UNLOCK_PATH = [
  {
    day: 3,
    title: 'First win',
    description: 'Sage starts remembering you',
    detail: 'Sage begins referencing your journal entries in responses. Everything gets more personal from here.',
  },
  {
    day: 7,
    title: 'Week complete',
    description: 'Your first weekly pulse',
    detail: 'Sage gives you one pattern from your first week that you would not have seen yourself.',
  },
  {
    day: 14,
    title: 'Consistency confirmed',
    description: 'Your statistics activate',
    detail: 'See your real completion rate, your best days, and your weakest patterns.',
  },
  {
    day: 30,
    title: 'One month in',
    description: 'Your monthly report',
    detail: 'One page. What shifted, what you built, what to focus on next. Generated by Sage from everything you shared.',
  },
  {
    day: 60,
    title: 'Depth unlocked',
    description: 'The harder journal templates',
    detail: 'Reality Check and Unsent Message unlock. Sage only gives these to people who have shown they can handle honesty.',
  },
  {
    day: 90,
    title: 'Identity',
    description: 'Your Phase 1 Legacy card',
    detail: 'Who you were when you started versus who you are now. Written by Sage in your own words.',
  },
  {
    day: 120,
    title: 'Mastery',
    description: 'Mastery insights',
    detail: 'Advanced insights, deeper pattern recognition, and long-term tracking.',
  },
]

const UNLOCK_CARD_HIDE_KEY = 'phasr_unlock_card_hidden_until'
const UNLOCKED_MILESTONES_KEY = 'phasr_unlocked_milestones'
const UNLOCK_MILESTONE_INDEX_KEY = 'phasr_unlock_milestone_index'
const UNLOCK_BASELINE_DAYS_KEY = 'phasr_unlock_baseline_days'
function getTodayIso() {
  return new Date().toISOString().slice(0, 10)
}

function getTomorrowIso() {
  const next = new Date()
  next.setDate(next.getDate() + 1)
  return next.toISOString().slice(0, 10)
}

function getRankMood(streak) {
  if (streak >= 120) return { label: 'Mastery', sublabel: 'deeply consistent' }
  if (streak >= 90) return { label: 'Identity', sublabel: 'becoming solid' }
  if (streak >= 30) return { label: 'Committed', sublabel: 'showing up fully' }
  if (streak >= 7) return { label: 'Rising', sublabel: 'building habits' }
  return { label: 'Beginner', sublabel: 'starting out' }
}

function getStageLevel(streak) {
  if (streak >= 120) return { level: 7, label: 'Mastery', sublabel: 'long-term insight' }
  if (streak >= 90) return { level: 6, label: 'Identity', sublabel: 'legacy unlocked' }
  if (streak >= 60) return { level: 5, label: 'Depth', sublabel: 'harder truths open' }
  if (streak >= 30) return { level: 4, label: 'Momentum', sublabel: 'reports unlocked' }
  if (streak >= 14) return { level: 3, label: 'Pattern', sublabel: 'stats are live' }
  if (streak >= 7) return { level: 2, label: 'Pulse', sublabel: 'weekly reflection active' }
  return { level: 1, label: 'Starter', sublabel: 'learning you' }
}

function safeRead(key, fallback) {
  try {
    const raw = localStorage.getItem(key)
    return raw ? JSON.parse(raw) : fallback
  } catch {
    return fallback
  }
}

function safeWrite(key, value) {
  localStorage.setItem(key, JSON.stringify(value))
}

function normalizeLabel(value) {
  return String(value || '').toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim()
}

function buildFingerprint(phase) {
  const text = [
    phase?.id || '',
    phase?.name || '',
    phase?.startDate || '',
    phase?.endDate || '',
    ...(Array.isArray(phase?.pillars) ? phase.pillars.flatMap((pillar, index) => [
      pillar?.id || index,
      pillar?.name || '',
    ]) : []),
  ].join('|')
  let hash = 0
  for (let i = 0; i < text.length; i += 1) hash = ((hash << 5) - hash + text.charCodeAt(i)) | 0
  return `${phase?.id || 'phase'}_${Math.abs(hash)}`
}

function hasConfiguredPillars(phase) {
  const pillars = Array.isArray(phase?.pillars) ? phase.pillars : []
  return pillars.some(pillar => {
    const activities = Array.isArray(pillar?.activities) ? pillar.activities.filter(Boolean) : []
    const weeklyActions = Array.isArray(pillar?.weeklyActions) ? pillar.weeklyActions.filter(Boolean) : []
    return activities.length > 0 || weeklyActions.length > 0 || pillar?.beforeImage || pillar?.afterImage || pillar?.beforeState || pillar?.afterState
  })
}

function buildActivities(phase) {
  const pillars = Array.isArray(phase?.pillars) ? phase.pillars : []
  return pillars.flatMap((pillar, pillarIndex) =>
    (Array.isArray(pillar?.activities) ? pillar.activities : [])
      .map((item, activityIndex) => {
        const description = String(item || '').trim()
        if (!description) return null
        return {
          id: `${pillar?.id || `pillar-${pillarIndex}`}_act${activityIndex}`,
          description,
          pillar: String(pillar?.name || `Pillar ${pillarIndex + 1}`).trim(),
        }
      })
      .filter(Boolean)
  )
}

function buildNonNegotiables(phase) {
  const pillars = Array.isArray(phase?.pillars) ? phase.pillars : []
  return pillars.flatMap((pillar, pillarIndex) =>
    (Array.isArray(pillar?.weeklyActions) ? pillar.weeklyActions : [])
      .map((item, nonNegIndex) => {
        const description = String(item || '').trim()
        if (!description) return null
        return {
          id: `${pillar?.id || `pillar-${pillarIndex}`}_nn${nonNegIndex}`,
          description,
          pillar: String(pillar?.name || `Pillar ${pillarIndex + 1}`).trim(),
        }
      })
      .filter(Boolean)
  )
}

function pulseDoneForWeek(phaseName, weekNumber) {
  const entries = safeRead('phasr_journal_v2', [])
  const phaseKey = normalizeLabel(phaseName)
  const fromEntries = entries.some(entry => {
    const metaWeek = Number(entry?.weeklyPulseMeta?.weekNumber || 0)
    const metaPhase = normalizeLabel(entry?.weeklyPulseMeta?.phaseName || '')
    const title = String(entry?.title || '').toLowerCase()
    return (metaWeek === weekNumber || (title.includes('weekly pulse') && title.includes(`week ${weekNumber}`))) &&
      (!metaPhase || metaPhase === phaseKey)
  })
  return fromEntries || localStorage.getItem(`phasr_weekly_pulse_w${weekNumber}_done`) === 'true'
}

function isQuarterlyReviewComplete(phase) {
  const fields = [
    phase?.reviewWorked,
    phase?.reviewDrained,
    phase?.reviewPaid,
    phase?.reviewStrategy,
  ]
  return fields.every(value => String(value || '').trim().length > 0)
}

function taskKey(week, day) {
  return `phasr_tasks_w${week}_d${day}`
}

function weekStartKey(scope, week) {
  return `phasr_week_start_${scope}_w${week}`
}

function getWeekStartDate(scope, week) {
  const today = new Date().toISOString().slice(0, 10)
  const key = weekStartKey(scope, week)
  const saved = localStorage.getItem(key)
  if (saved) return saved
  localStorage.setItem(key, today)
  return today
}

function nonNegCompleteKey(week, nonNegIndex) {
  return `phasr_nn_complete_w${week}_nn${nonNegIndex}`
}

function parseNonNegotiable(text) {
  const numericMatch = text.match(/(\d[\d,]*)\s*(steps?|calories?|reps?|minutes?|hours?|pages?|words?)/i)
  if (numericMatch) {
    return {
      type: 'numeric',
      target: parseInt(numericMatch[1].replace(/,/g, ''), 10),
      unit: numericMatch[2].toLowerCase(),
      text,
    }
  }

  const freqMatch = text.match(/(\d+)\s*times?\s*(a\s*)?(week|weekly)/i)
  if (freqMatch) {
    return {
      type: 'frequency',
      timesPerWeek: parseInt(freqMatch[1], 10),
      text,
    }
  }

  return { type: 'habit', text }
}

function generateWeekSchedule(nonNeg) {
  const parsed = parseNonNegotiable(nonNeg.description)
  const schedule = {}

  if (parsed.type === 'numeric') {
    const avg = parsed.target / 7
    const dailyAmounts = [
      Math.round(avg * 0.7),
      Math.round(avg * 0.8),
      Math.round(avg * 0.9),
      Math.round(avg * 1.0),
      Math.round(avg * 1.1),
      Math.round(avg * 1.2),
      Math.round(avg * 1.3),
    ]
    const total = dailyAmounts.reduce((sum, amount) => sum + amount, 0)
    const scale = total ? parsed.target / total : 1
    const scaled = dailyAmounts.map(amount => Math.round(amount * scale))
    const diff = parsed.target - scaled.reduce((sum, amount) => sum + amount, 0)
    if (scaled.length) scaled[scaled.length - 1] += diff

    for (let day = 1; day <= 7; day += 1) {
      schedule[day] = `${Math.max(0, scaled[day - 1]).toLocaleString()} ${parsed.unit} today`
    }
  }

  if (parsed.type === 'frequency') {
    const frequencyDayMap = {
      7: [1, 2, 3, 4, 5, 6, 7],
      6: [1, 2, 3, 4, 5, 6],
      5: [1, 2, 3, 5, 6],
      4: [1, 2, 4, 6],
      3: [1, 3, 5],
      2: [2, 5],
      1: [3],
    }
    const activeDays = frequencyDayMap[parsed.timesPerWeek] || frequencyDayMap[3]
    for (let day = 1; day <= 7; day += 1) {
      schedule[day] = activeDays.includes(day)
        ? nonNeg.description.replace(/\d+\s*times?\s*(a\s*)?(week|weekly)/i, 'today')
        : null
    }
  }

  if (parsed.type === 'habit') {
    const isDaily = /daily|every day|each day/i.test(nonNeg.description)
    for (let day = 1; day <= 7; day += 1) {
      schedule[day] = isDaily ? nonNeg.description : (day === 3 ? nonNeg.description : null)
    }
  }

  return schedule
}

function getScheduleKey(weekNumber, nonNegIndex) {
  return `phasr_schedule_w${weekNumber}_nn${nonNegIndex}`
}

function buildDayTasks(activities, weekNumber, dayNumber) {
  return activities.map((activity, activityIndex) => ({
    id: `act${activityIndex}_w${weekNumber}_d${dayNumber}`,
    description: activity.description,
    pillar: activity.pillar,
    done: false,
  }))
}

function sameTaskShape(savedTasks, nextTasks) {
  if (!Array.isArray(savedTasks) || savedTasks.length !== nextTasks.length) return false
  return savedTasks.every((task, index) =>
    task?.id === nextTasks[index]?.id &&
    task?.description === nextTasks[index]?.description &&
    task?.pillar === nextTasks[index]?.pillar
  )
}

function mergeTaskProgress(savedTasks, nextTasks) {
  const savedMap = new Map((savedTasks || []).map(task => [task.id, task]))
  return nextTasks.map(task => ({
    ...task,
    done: Boolean(savedMap.get(task.id)?.done),
  }))
}

function getTodaysTasks(activities, weekNumber, dayNumber) {
  const cacheKey = taskKey(weekNumber, dayNumber)
  const cached = safeRead(cacheKey, null)
  const baseTasks = buildDayTasks(activities, weekNumber, dayNumber)

  if (sameTaskShape(cached, baseTasks)) return cached

  const nextTasks = Array.isArray(cached)
    ? mergeTaskProgress(cached, baseTasks)
    : baseTasks

  safeWrite(cacheKey, nextTasks)
  return nextTasks
}

function checkNonNegComplete(nonNegIndex, weekNumber) {
  let allDone = true
  let foundTask = false
  for (let day = 1; day <= 7; day += 1) {
    const tasks = safeRead(taskKey(weekNumber, day), [])
    const nonNegTask = tasks.find(task => task.nonNegIndex === nonNegIndex)
    if (nonNegTask) {
      foundTask = true
      if (!nonNegTask.done) {
        allDone = false
        break
      }
    }
  }
  if (foundTask && allDone) {
    localStorage.setItem(nonNegCompleteKey(weekNumber, nonNegIndex), 'true')
  }
}

function countDaysDone(week, dayLimit = 7) {
  let done = 0
  for (let day = 1; day <= dayLimit; day += 1) {
    const isDone = localStorage.getItem(`phasr_streak_w${week}_d${day}`) === 'true'
    if (isDone) done += 1
  }
  return done
}

function countWeekTasksDone(week) {
  let done = 0
  for (let day = 1; day <= 7; day += 1) {
    const tasks = safeRead(taskKey(week, day), [])
    done += tasks.filter(item => item.done).length
  }
  return done
}

function countWeekTasksAssigned(week) {
  let assigned = 0
  for (let day = 1; day <= 7; day += 1) {
    const tasks = safeRead(taskKey(week, day), [])
    assigned += Array.isArray(tasks) ? tasks.length : 0
  }
  return assigned
}

export default function DailyCheckin({ onLockInChange, onOpenBoard, onOpenWeeklyPulse, onOpenQuarterlyReview }) {
  const [lockInState, setLockInState] = useState(() => loadLockInState())
  const [userLevel, setUserLevel] = useState(() => getStoredUserLevel() || calculateUserPoints())
  const [refresh, setRefresh] = useState(0)
  const [sageCardExpanded, setSageCardExpanded] = useState(true)
  const [unlockCardState, setUnlockCardState] = useState('active')
  const [displayMilestoneDay, setDisplayMilestoneDay] = useState(UNLOCK_PATH[0].day)
  const [unlockedMilestones, setUnlockedMilestones] = useState(() => safeRead(UNLOCKED_MILESTONES_KEY, []))
  const [unlockMilestoneIndex, setUnlockMilestoneIndex] = useState(() => Number(localStorage.getItem(UNLOCK_MILESTONE_INDEX_KEY) || 0) || 0)
  const [unlockBaselineDays, setUnlockBaselineDays] = useState(() => Number(localStorage.getItem(UNLOCK_BASELINE_DAYS_KEY) || 0) || 0)
  const [recentlyUnlockedDay, setRecentlyUnlockedDay] = useState(null)
  const [unlockNotice, setUnlockNotice] = useState('')
  const [unlockCardVisible, setUnlockCardVisible] = useState(() => {
    if (typeof window === 'undefined') return true
    const hiddenUntil = localStorage.getItem(UNLOCK_CARD_HIDE_KEY)
    return !hiddenUntil || hiddenUntil <= getTodayIso()
  })
  const [unlockHovering, setUnlockHovering] = useState(false)
  const unlockTimersRef = useRef({ transition: null, enter: null })
  const unlockHideTapRef = useRef(0)

  useEffect(() => {
    const sync = () => {
      setLockInState(loadLockInState())
      setUserLevel(getStoredUserLevel() || calculateUserPoints())
      setRefresh(value => value + 1)
    }
    window.addEventListener('focus', sync)
    window.addEventListener('storage', sync)
    window.addEventListener('phasr-user-level-updated', sync)
    return () => {
      window.removeEventListener('focus', sync)
      window.removeEventListener('storage', sync)
      window.removeEventListener('phasr-user-level-updated', sync)
    }
  }, [])

  const boardData = useMemo(() => loadBoardData(), [refresh])
  const phases = useMemo(() => {
    const next = Array.isArray(boardData?.phases) ? [...boardData.phases] : []
    next.sort((a, b) => {
      const aNum = Number(String(a?.name || '').replace(/[^\d]/g, '')) || 999
      const bNum = Number(String(b?.name || '').replace(/[^\d]/g, '')) || 999
      return aNum - bNum
    })
    return next
  }, [boardData])
  const [activePhaseId, setActivePhaseId] = useState(() => boardData?.activePhaseId || phases[0]?.id || null)

  useEffect(() => {
    if (!phases.some(phase => phase.id === activePhaseId)) {
      setActivePhaseId(boardData?.activePhaseId || phases[0]?.id || null)
    }
  }, [activePhaseId, boardData, phases])

  const phaseBoard = useMemo(() => ({ ...(boardData || {}), activePhaseId }), [boardData, activePhaseId])
  const weeklyData = useMemo(() => buildWeeklyGoals(phaseBoard, lockInState), [phaseBoard, lockInState])
  const currentPhase = phases.find(phase => phase.id === activePhaseId) || phases[0] || null
  const hasPillars = hasConfiguredPillars(currentPhase)
  const activities = useMemo(() => buildActivities(currentPhase), [currentPhase])
  const nonNegotiables = useMemo(() => buildNonNegotiables(currentPhase), [currentPhase])
  const phaseScope = useMemo(() => buildFingerprint(currentPhase || {}), [currentPhase])
  const totalWeeks = Math.max(weeklyData.weeks?.length || 1, 1)
  const [activeWeek, setActiveWeek] = useState(1)
  const [tasks, setTasks] = useState([])
  const [showPhaseModal, setShowPhaseModal] = useState(false)
  const [lockedWeekMessage, setLockedWeekMessage] = useState('')

  const weekStatuses = useMemo(() => {
    return (weeklyData.weeks || []).map(item => {
      const daysDone = hasPillars ? countDaysDone(item.index) : 0
      const pulseDone = pulseDoneForWeek(currentPhase?.name, item.index) && daysDone === 7
      return {
        week: item.index,
        daysDone,
        pulseDone,
      }
    })
  }, [weeklyData.weeks, hasPillars, currentPhase, tasks, refresh])
  const phaseStart = useMemo(() => {
    const stored = localStorage.getItem('phasr_phase1_start_date')
    if (stored) return stored
    const fallback = currentPhase?.startDate || new Date().toISOString().slice(0, 10)
    localStorage.setItem('phasr_phase1_start_date', fallback)
    return fallback
  }, [currentPhase?.startDate])
  const elapsedPhaseDays = useMemo(() => {
    const startMs = new Date(phaseStart).getTime()
    if (!Number.isFinite(startMs)) return 0
    return Math.max(0, Math.floor((Date.now() - startMs) / 86400000))
  }, [phaseStart])
  const currentWeek = useMemo(() => Math.min(totalWeeks, Math.floor(elapsedPhaseDays / 7) + 1), [elapsedPhaseDays, totalWeeks])
  const currentDayNumber = useMemo(() => Math.min((elapsedPhaseDays % 7) + 1, 7), [elapsedPhaseDays])

  useEffect(() => {
    setActiveWeek(currentWeek)
  }, [currentWeek, activePhaseId])

  useEffect(() => {
    localStorage.setItem('phasr_current_week', String(currentWeek))
  }, [currentWeek])

  const week = weeklyData.weeks.find(item => item.index === activeWeek) || weeklyData.weeks[0] || null
  const displayedDay = activeWeek < currentWeek ? 7 : activeWeek > currentWeek ? 1 : currentDayNumber

  useEffect(() => {
    if (!hasPillars || !week) {
      setTasks([])
      return
    }
    setTasks(getTodaysTasks(activities, activeWeek, displayedDay))
  }, [hasPillars, week, activities, displayedDay, activeWeek])

  const todaysTasks = useMemo(() => safeRead(taskKey(activeWeek, displayedDay), []), [activeWeek, displayedDay, tasks, refresh])
  const completedToday = todaysTasks.filter(task => task.done).length
  const totalToday = todaysTasks.length
  const daysCompleted = useMemo(() => hasPillars ? countDaysDone(activeWeek, displayedDay) : 0, [hasPillars, activeWeek, displayedDay, tasks])
  const completedTasksThisWeek = useMemo(() => hasPillars ? countWeekTasksDone(activeWeek) : 0, [hasPillars, activeWeek, tasks])
  const totalTasksThisWeek = useMemo(() => hasPillars ? countWeekTasksAssigned(activeWeek) : 0, [hasPillars, activeWeek, tasks])
  const weekPercent = totalTasksThisWeek ? Math.round((completedTasksThisWeek / totalTasksThisWeek) * 100) : 0
  const currentPulseDone = weekStatuses.find(item => item.week === activeWeek)?.pulseDone || false
  const previousPulseDone = activeWeek === 1 ? true : (weekStatuses.find(item => item.week === activeWeek - 1)?.pulseDone || false)
  const isNewUser = activeWeek === 1 && displayedDay === 1 && completedTasksThisWeek === 0
  const showReminder = activeWeek > 1 && displayedDay > 1 && !previousPulseDone
  const weekComplete = daysCompleted === 7
  const isMobile = typeof window !== 'undefined' ? window.innerWidth <= 768 : false
  const accent = 'var(--app-accent)'
  const accent2 = 'var(--app-accent2)'

  function hideUnlockPathForToday() {
    localStorage.setItem(UNLOCK_CARD_HIDE_KEY, getTomorrowIso())
    setUnlockCardVisible(false)
  }

  function handleUnlockPathPointerUp(event) {
    if (!isMobile) return
    if (event.pointerType && event.pointerType !== 'touch') return
    const now = Date.now()
    if (now - unlockHideTapRef.current < 320) {
      hideUnlockPathForToday()
    }
    unlockHideTapRef.current = now
  }
  const currentStreak = useMemo(() => {
    let streak = 0
    for (let weekNumber = 1; weekNumber <= currentWeek; weekNumber += 1) {
      const limit = weekNumber === currentWeek ? currentDayNumber : 7
      streak += countDaysDone(weekNumber, limit)
    }
    return streak
  }, [currentWeek, currentDayNumber, tasks, refresh])
  const overallDaysDone = useMemo(() => {
    let total = 0
    for (let weekNumber = 1; weekNumber <= currentWeek; weekNumber += 1) {
      const limit = weekNumber === currentWeek ? currentDayNumber : 7
      total += countDaysDone(weekNumber, limit)
    }
    return total
  }, [currentWeek, currentDayNumber, tasks, refresh])
  const rankMood = getRankMood(currentStreak)
  const stageLevel = getStageLevel(currentStreak)
  const progressStreak = isNewUser ? 0 : currentStreak
  const normalizedUnlocked = Array.isArray(unlockedMilestones) ? unlockedMilestones.filter(Number.isFinite) : []
  const latestUnlocked = [...UNLOCK_PATH].reverse().find(item => normalizedUnlocked.includes(item.day)) || null
  const inferredBaselineDays = useMemo(() => normalizedUnlocked.reduce((sum, day) => sum + day, 0), [normalizedUnlocked])
  const safeBaselineDays = useMemo(() => {
    const baseline = Number.isFinite(unlockBaselineDays) ? unlockBaselineDays : 0
    if (baseline < 0) return 0
    if (baseline > overallDaysDone && inferredBaselineDays <= overallDaysDone) return inferredBaselineDays
    return baseline
  }, [unlockBaselineDays, overallDaysDone, inferredBaselineDays])
  const progressDays = currentStreak
  const upcomingMilestone = UNLOCK_PATH[Math.min(Math.max(0, unlockMilestoneIndex), UNLOCK_PATH.length - 1)] || UNLOCK_PATH[0]
  const displayedMilestone = UNLOCK_PATH.find(item => item.day === displayMilestoneDay) || upcomingMilestone
  const progress = displayedMilestone ? Math.max(0, Math.min(1, currentStreak / displayedMilestone.day)) : 1
  const progressPercent = displayedMilestone ? Math.max(0, Math.min(100, Math.round((currentStreak / displayedMilestone.day) * 100))) : 100
  const daysLeft = displayedMilestone ? Math.max(0, displayedMilestone.day - currentStreak) : 0
  const milestoneActivated = Boolean(displayedMilestone && (normalizedUnlocked.includes(displayedMilestone.day) || recentlyUnlockedDay === displayedMilestone.day))

  useEffect(() => {
    safeWrite(UNLOCKED_MILESTONES_KEY, normalizedUnlocked)
  }, [normalizedUnlocked])

  useEffect(() => {
    // Keep the new milestone system stable for existing users by inferring baseline from unlocked milestones once.
    if (!localStorage.getItem(UNLOCK_BASELINE_DAYS_KEY) && inferredBaselineDays > 0) {
      localStorage.setItem(UNLOCK_BASELINE_DAYS_KEY, String(inferredBaselineDays))
      setUnlockBaselineDays(inferredBaselineDays)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [inferredBaselineDays])

  useEffect(() => {
    localStorage.setItem(UNLOCK_MILESTONE_INDEX_KEY, String(Math.max(0, Math.min(unlockMilestoneIndex, UNLOCK_PATH.length - 1))))
  }, [unlockMilestoneIndex])

  useEffect(() => {
    localStorage.setItem(UNLOCK_BASELINE_DAYS_KEY, String(Math.max(0, safeBaselineDays)))
  }, [safeBaselineDays])

  useEffect(() => {
    const unlockState = {
      streakDays: currentStreak,
      completedActionsThisWeek: completedTasksThisWeek,
      rank: rankMood.label,
      rankSubtitle: rankMood.sublabel,
      stageLevel: stageLevel.level,
      stageLabel: stageLevel.label,
      personalizedSageMemory: normalizedUnlocked.includes(3),
      weeklyPulseUnlocked: normalizedUnlocked.includes(7),
      statisticsUnlocked: normalizedUnlocked.includes(14),
      monthlyReportUnlocked: normalizedUnlocked.includes(30),
      deeperTemplatesUnlocked: normalizedUnlocked.includes(60),
      phaseLegacyUnlocked: normalizedUnlocked.includes(90),
      masteryInsightsUnlocked: normalizedUnlocked.includes(120),
      unlockedDays: normalizedUnlocked,
    }

    localStorage.setItem('phasr_unlock_state', JSON.stringify(unlockState))
    window.dispatchEvent(new CustomEvent('phasr-unlocks-updated', { detail: unlockState }))
  }, [currentStreak, completedTasksThisWeek, normalizedUnlocked, rankMood.label, rankMood.sublabel, stageLevel.level, stageLevel.label])

  useEffect(() => {
    const hiddenUntil = localStorage.getItem(UNLOCK_CARD_HIDE_KEY)
    setUnlockCardVisible(!hiddenUntil || hiddenUntil <= getTodayIso())
  }, [refresh, currentStreak])

  useEffect(() => {
    // Unlocks are sequential; milestone index tracks the next interval milestone.
    const nextIndex = Math.min(normalizedUnlocked.length, UNLOCK_PATH.length - 1)
    if (nextIndex !== unlockMilestoneIndex) setUnlockMilestoneIndex(nextIndex)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [normalizedUnlocked])

  useEffect(() => {
    setDisplayMilestoneDay(upcomingMilestone.day)
    setUnlockCardState('active')
  }, [upcomingMilestone.day])

  function canAccessWeek(weekNumber) {
    if (weekNumber === 1) return true
    const previous = weekStatuses.find(item => item.week === weekNumber - 1)
    return Boolean(previous?.pulseDone)
  }

  function toggleTask(taskId) {
    const allDoneBefore = tasks.length > 0 && tasks.every(item => item.done)
    const updated = tasks.map(item => item.id === taskId ? { ...item, done: !item.done } : item)
    safeWrite(taskKey(activeWeek, displayedDay), updated)
    setTasks(updated)
    setLockInState(loadLockInState())
    onLockInChange?.()

    const milestone = displayedMilestone
    const allDoneToday = updated.length > 0 && updated.every(item => item.done)
    if (allDoneToday && updated.length > 0) {
      localStorage.setItem(`phasr_streak_w${activeWeek}_d${displayedDay}`, 'true')
    } else {
      localStorage.setItem(`phasr_streak_w${activeWeek}_d${displayedDay}`, 'false')
    }
    const task = updated.find(item => item.id === taskId)
    if (task) checkNonNegComplete(task.nonNegIndex, activeWeek)
    setUserLevel(calculateUserPoints())

    const dayJustCompleted = allDoneToday && !allDoneBefore
    const projectedOverallDaysDone = overallDaysDone + (dayJustCompleted ? 1 : 0)
    const projectedStreak = dayJustCompleted ? Math.max(currentStreak, currentStreak + 1) : currentStreak

    if (milestone && allDoneToday && projectedStreak >= milestone.day) {
      unlockMilestoneNow(milestone.day, projectedOverallDaysDone)
    }
  }

  function unlockMilestoneNow(milestoneDay, nextBaselineDays) {
    if (!milestoneDay) return
    if (normalizedUnlocked.includes(milestoneDay)) return

    setRecentlyUnlockedDay(milestoneDay)
    setUnlockedMilestones(prev => {
      const list = Array.isArray(prev) ? prev.slice() : []
      if (!list.includes(milestoneDay)) list.push(milestoneDay)
      return list.sort((a, b) => a - b)
    })

    setUnlockCardState('unlock')
    setDisplayMilestoneDay(milestoneDay)
    const milestone = UNLOCK_PATH.find(item => item.day === milestoneDay)
    if (milestone) {
      setUnlockNotice(`${milestone.title} is now available.`)
    }
    if (Number.isFinite(nextBaselineDays)) setUnlockBaselineDays(Math.max(0, Number(nextBaselineDays)))

    if (unlockTimersRef.current.transition) window.clearTimeout(unlockTimersRef.current.transition)
    if (unlockTimersRef.current.enter) window.clearTimeout(unlockTimersRef.current.enter)

    unlockTimersRef.current.transition = window.setTimeout(() => setUnlockCardState('transition'), 1400)
    unlockTimersRef.current.enter = window.setTimeout(() => {
      const currentIndex = UNLOCK_PATH.findIndex(item => item.day === milestoneDay)
      const nextIndex = Math.min(Math.max(0, currentIndex + 1), UNLOCK_PATH.length - 1)
      const upcoming = UNLOCK_PATH[nextIndex] || UNLOCK_PATH[UNLOCK_PATH.length - 1]
      setUnlockMilestoneIndex(nextIndex)
      setDisplayMilestoneDay(upcoming.day)
      setUnlockCardState('active')
      setRecentlyUnlockedDay(null)
    }, 1650)
  }

  // If the user already completed today's tasks, unlock immediately (no extra tap required).
  useEffect(() => {
    const milestone = displayedMilestone
    if (!hasPillars || !milestone) return
    if (normalizedUnlocked.includes(milestone.day)) return
    const allDoneToday = tasks.length > 0 && tasks.every(item => item.done)
    if (!allDoneToday) return
    if (currentStreak < milestone.day) return
    unlockMilestoneNow(milestone.day, overallDaysDone)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tasks, hasPillars, displayedMilestone?.day, currentStreak, overallDaysDone, normalizedUnlocked.join('|')])

  function getPhaseLabel(phaseId) {
    const index = phases.findIndex(phase => phase.id === phaseId)
    return `Phase ${Math.max(1, index + 1)}`
  }

  function openPulse() {
    onOpenWeeklyPulse?.({
      weekNumber: activeWeek,
      completionPercent: weekPercent,
      tasksCompleted: completedTasksThisWeek,
      tasksTotal: totalTasksThisWeek,
      phaseName: getPhaseLabel(activePhaseId),
    })
  }

  function openQuarterlyReview() {
    onOpenQuarterlyReview?.(currentPhase)
  }

  function handlePhaseChange(nextPhaseId) {
    if (nextPhaseId === activePhaseId) {
      onOpenBoard?.()
      return
    }
    const currentIndex = phases.findIndex(item => item.id === activePhaseId)
    const nextIndex = phases.findIndex(item => item.id === nextPhaseId)
    if (currentIndex >= 0 && nextIndex > currentIndex) {
      if (!isQuarterlyReviewComplete(currentPhase)) {
        setShowPhaseModal(true)
        return
      }
    }
    setActivePhaseId(nextPhaseId)
  }

  return (
    <div style={{ minHeight: 'calc(100vh - 56px)', background: 'var(--app-bg)', color: 'var(--app-text)', width: '100%', overflowX: 'hidden', display: 'flex', justifyContent: 'center' }}>
      <div style={{ width: 'min(100%, 1080px)', maxWidth: '100%', margin: '0 auto', padding: isMobile ? '14px 10px 96px' : '18px 20px 96px', boxSizing: 'border-box' }}>
        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
          {phases.map((phase, index) => (
            <button
              key={phase.id}
              type="button"
              onClick={() => handlePhaseChange(phase.id)}
              style={{
                padding: '10px 18px',
                borderRadius: 999,
                border: phase.id === activePhaseId ? '1px solid transparent' : '1px solid #f2c8d6',
                background: phase.id === activePhaseId ? `linear-gradient(135deg,${accent2},${accent})` : '#fff',
                color: phase.id === activePhaseId ? '#fff' : 'var(--app-text)',
                fontFamily: "'Syne', sans-serif",
                fontSize: 13,
                fontWeight: 700,
                cursor: 'pointer',
              }}
            >
              {`Phase ${index + 1}`}
            </button>
          ))}
        </div>

        <div style={{ height: 16 }} />

        <div style={{ background: '#fff', border: '1.5px solid #f2c4d0', borderRadius: 16, padding: '1rem', marginBottom: '1rem' }}>
          <div
            onClick={() => setSageCardExpanded(value => !value)}
            style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8, cursor: 'pointer' }}
            title={sageCardExpanded ? 'Collapse' : 'Expand'}
          >
            <div style={{ width: 28, height: 28, borderRadius: '50%', background: 'linear-gradient(135deg, #e8407a, #f472a8)', display: 'grid', placeItems: 'center', color: '#fff', fontWeight: 800, fontSize: '0.55rem' }}>SAGE</div>
            <p style={{ fontSize: '0.65rem', fontWeight: 700, color: '#e8407a' }}>Live Score</p>
            <p style={{ fontSize: '0.65rem', color: '#b08090', marginLeft: 'auto' }}>{weekPercent}% this week</p>
          </div>

          {!sageCardExpanded && (
            <p style={{ margin: 0, fontSize: '0.82rem', color: '#3d1f2b', lineHeight: 1.6 }}>
              {hasPillars ? `Day ${displayedDay} of 7. ${weekPercent >= 50 ? 'You are on track.' : 'Stay consistent.'}` : 'Add pillar activities in Vision Board to activate your streak.'}
            </p>
          )}

          {sageCardExpanded && (
            <>
          {!hasPillars && (
            <p style={{ fontSize: '0.82rem', color: '#3d1f2b', lineHeight: 1.6 }}>
              Add your pillar activities in Vision Board and they will appear in your daily to-do automatically.
            </p>
          )}
          {hasPillars && isNewUser && (
            <p style={{ fontSize: '0.82rem', color: '#3d1f2b', lineHeight: 1.6 }}>
              Your week 1 starts today. Complete your daily tasks and come back tomorrow. Sage will track your progress and guide you as the week builds.
            </p>
          )}
          {hasPillars && !isNewUser && weekComplete && !currentPulseDone && (
            <>
              <p style={{ fontSize: '0.82rem', color: '#3d1f2b', lineHeight: 1.6, marginBottom: 12 }}>
                Week {activeWeek} closed at {weekPercent}%. Complete your weekly reflection with Sage before week {activeWeek + 1} opens.
              </p>
              <button onClick={openPulse} style={{ width: '100%', padding: '0.7rem', borderRadius: 12, border: 'none', background: 'linear-gradient(135deg, #e8407a, #f472a8)', color: '#fff', fontSize: '0.82rem', fontWeight: 700, cursor: 'pointer' }}>
                Open Weekly Pulse
              </button>
            </>
          )}
          {hasPillars && !isNewUser && weekComplete && currentPulseDone && (
            <p style={{ fontSize: '0.82rem', color: '#3d1f2b', lineHeight: 1.6 }}>
              Week {activeWeek} done. Reflection complete. Week {activeWeek + 1} is open.
            </p>
          )}
          {hasPillars && !isNewUser && !weekComplete && showReminder && (
            <p style={{ fontSize: '0.82rem', color: '#3d1f2b', lineHeight: 1.6 }}>
              You are {displayedDay} days into week {activeWeek}. Your week {activeWeek - 1} reflection with Sage is still pending.
              <span onClick={openPulse} style={{ color: '#e8407a', fontWeight: 700, cursor: 'pointer' }}> Complete now</span>
            </p>
          )}
          {hasPillars && !isNewUser && !weekComplete && !showReminder && (
              <p style={{ fontSize: '0.82rem', color: '#3d1f2b', lineHeight: 1.6 }}>
              Day {displayedDay} of 7. You have completed {completedTasksThisWeek} of {totalTasksThisWeek} tasks this week.
              {weekPercent >= 50 ? ' You are on track. Keep going.' : ' Stay consistent. Every task counts.'}
            </p>
          )}
            </>
          )}
        </div>

        {!hasPillars && (
          <div style={{ textAlign: 'center', padding: '1.5rem 1rem', border: '1px solid #f2c8d6', borderRadius: 16, background: '#fff6f9', marginBottom: '1rem' }}>
            <p style={{ fontSize: '1rem', fontWeight: 700, color: '#3d1f2b', marginBottom: 8 }}>Set up your Vision Board first</p>
            <p style={{ fontSize: '0.82rem', color: '#7a5a66', lineHeight: 1.6, marginBottom: 12 }}>
              Your daily tasks come from your pillar activities. Add them to your Vision Board to activate your streak.
            </p>
            <button type="button" onClick={onOpenBoard} style={{ borderRadius: 999, border: `1px solid ${accent}`, background: 'transparent', color: accent, padding: '0.55rem 0.95rem', fontWeight: 700, fontSize: 12, cursor: 'pointer' }}>
              Go to Vision Board
            </button>
          </div>
        )}

        <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', color: '#7e5d68', marginBottom: 10 }}>All Weeks</div>
        <div style={{ overflowX: 'auto', paddingBottom: 2 }}>
          <div style={{ display: 'flex', gap: 8, width: 'max-content', minWidth: '100%' }}>
            {weeklyData.weeks.map(item => {
              const active = item.index === activeWeek
              const locked = !canAccessWeek(item.index)
              const pulseDone = weekStatuses.find(weekItem => weekItem.week === item.index)?.pulseDone || false
              return (
                <button
                  key={item.id}
                  type="button"
                  onClick={() => {
                    if (locked) {
                      setLockedWeekMessage(`Finish Week ${item.index - 1} and complete its weekly reflection with Sage first.`)
                      return
                    }
                    setActiveWeek(item.index)
                  }}
                  style={{
                    padding: isMobile ? '7px 12px' : '8px 14px',
                    borderRadius: 999,
                    border: active ? `1px solid ${accent}` : '1px solid #f2c8d6',
                    background: active ? '#fff1f6' : '#fff',
                    color: active ? accent : 'var(--app-text)',
                    fontSize: isMobile ? 11 : 12,
                    fontWeight: 700,
                    cursor: 'pointer',
                    opacity: locked ? 0.7 : 1,
                    whiteSpace: 'nowrap',
                  }}
                >
                  {pulseDone ? `Week ${item.index} done` : `Week ${item.index}`}
                </button>
              )
            })}
          </div>
        </div>

        <div style={{ height: 14 }} />

        {lockedWeekMessage ? (
          <div style={{ background: '#fff8ec', border: '1px solid #f3d38a', borderRadius: 16, padding: '0.9rem 1rem', marginBottom: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 }}>
            <p style={{ margin: 0, fontSize: '0.82rem', color: '#5a4310', lineHeight: 1.5 }}>
              {lockedWeekMessage}
            </p>
            <button
              type="button"
              onClick={() => setLockedWeekMessage('')}
              style={{ border: 'none', background: 'transparent', color: '#9f7a18', fontWeight: 700, cursor: 'pointer' }}
            >
              OK
            </button>
          </div>
        ) : null}

        <div style={{ background: '#fff', border: '1px solid #f2c8d6', borderRadius: 22, padding: isMobile ? 14 : 18 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 14 }}>
            <div>
              <div style={{ fontSize: '0.82rem', fontWeight: 700, color: '#3d1f2b' }}>Daily To-Do</div>
              <div style={{ fontSize: '0.65rem', color: '#b08090' }}>Day {displayedDay} of 7</div>
            </div>
            <div style={{ fontSize: 12, fontWeight: 700, color: accent }}>{completedToday}/{totalToday}</div>
          </div>

          <div style={{ height: 8, borderRadius: 999, background: '#fff6f9', overflow: 'hidden', marginBottom: 10 }}>
            <div style={{ width: `${(daysCompleted / 7) * 100}%`, height: '100%', borderRadius: 999, background: `linear-gradient(90deg,${accent},${accent2})` }} />
          </div>

          <div style={{ fontSize: 11, color: '#7e5d68', marginBottom: 14 }}>
            {hasPillars ? 'These tasks are generated from your pillar activities and update with your daily streak progress.' : 'Set up your pillar activities first to activate your daily streak plan.'}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {tasks.length === 0 && (
              <div style={{ padding: '18px 16px', borderRadius: 14, border: '1px solid #f2c8d6', background: '#fff6f9', color: '#7e5d68', fontSize: 12 }}>
                {hasPillars ? 'Add activities to your pillar so your daily to-do can load.' : 'Set up your vision board first to activate your daily tasks.'}
              </div>
            )}
            {tasks.map(task => (
              <button
                key={task.id}
                type="button"
                onClick={() => toggleTask(task.id)}
                style={{
                  width: '100%',
                  display: 'flex',
                  alignItems: 'flex-start',
                  gap: 12,
                  padding: '14px 16px',
                  background: task.done ? '#ffe4ee' : '#fff6f9',
                  border: `1px solid ${task.done ? '#ef5d90' : '#f2c8d6'}`,
                  borderRadius: 14,
                  cursor: 'pointer',
                  textAlign: 'left',
                  opacity: 1,
                }}
              >
                <div style={{ width: 20, height: 20, borderRadius: '50%', border: `2px solid ${task.done ? '#ef5d90' : '#f2c8d6'}`, background: task.done ? '#ef5d90' : '#fff', color: '#fff', display: 'grid', placeItems: 'center', flexShrink: 0, marginTop: 2, fontSize: 11, fontWeight: 800, lineHeight: 1 }}>
                  {task.done ? '✓' : ''}
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: isMobile ? 14 : 16, fontWeight: 600, lineHeight: 1.45, color: task.done ? '#7e5d68' : 'var(--app-text)', textDecoration: task.done ? 'line-through' : 'none' }}>
                    {task.description}
                  </div>
                  <div style={{ fontSize: 12, color: '#7e5d68', marginTop: 4 }}>{task.pillar}</div>
                </div>
              </button>
            ))}
          </div>
        </div>

        <div style={{ height: 18 }} />

        <div style={{ background: '#fff', border: '1px solid #f2c8d6', borderRadius: 22, padding: isMobile ? 12 : 16 }}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: isMobile ? 10 : 12 }}>
            <div style={{ background: '#fff8fa', border: '1px solid #f2c8d6', borderRadius: 16, padding: isMobile ? '14px 10px' : '16px 12px', textAlign: 'center' }}>
              <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#b07a8e', marginBottom: 10 }}>Actions</div>
              <div style={{ fontFamily: "'Syne', sans-serif", fontSize: isMobile ? 16 : 28, fontWeight: 800, color: '#24131f', marginBottom: 4 }}>{completedTasksThisWeek}</div>
              <div style={{ fontSize: 11, color: '#8f6f7a' }}>done this week</div>
            </div>
            <div style={{ background: '#f7fff8', border: '1px solid #cfe7d5', borderRadius: 16, padding: isMobile ? '14px 10px' : '16px 12px', textAlign: 'center' }}>
              <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#8aa596', marginBottom: 10 }}>Rank</div>
              <div style={{ fontFamily: "'Syne', sans-serif", fontSize: isMobile ? 16 : 18, fontWeight: 800, color: '#24131f', marginBottom: 4 }}>{rankMood.label}</div>
              <div style={{ fontSize: 11, color: '#7f9388' }}>{rankMood.sublabel}</div>
            </div>
            <div style={{ background: '#faf7ff', border: '1px solid #d9cdee', borderRadius: 16, padding: isMobile ? '14px 10px' : '16px 12px', textAlign: 'center' }}>
              <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#9a8cb7', marginBottom: 10 }}>Sage Level</div>
              <div style={{ fontFamily: "'Syne', sans-serif", fontSize: isMobile ? 16 : 18, fontWeight: 800, color: '#24131f', marginBottom: 4 }}>{`Level ${stageLevel.level}`}</div>
              <div style={{ fontSize: 11, color: '#9a8cb7' }}>{stageLevel.label}</div>
            </div>
            <div style={{ background: '#f7fbff', border: '1px solid #cdddf0', borderRadius: 16, padding: isMobile ? '14px 10px' : '16px 12px', textAlign: 'center' }}>
              <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#7b93ae', marginBottom: 10 }}>Points</div>
              <div style={{ fontFamily: "'Syne', sans-serif", fontSize: isMobile ? 16 : 18, fontWeight: 800, color: '#24131f', marginBottom: 4 }}>{userLevel?.points || 0}</div>
              <div style={{ fontSize: 11, color: '#7b93ae' }}>{`Level ${userLevel?.level || 1} ${userLevel?.levelName || 'Starter'}`}</div>
            </div>
          </div>
        </div>

        <div style={{ height: 18 }} />

        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 }}>
          {!unlockCardVisible ? (
            <button
              type="button"
              onClick={() => {
                localStorage.removeItem(UNLOCK_CARD_HIDE_KEY)
                setUnlockCardVisible(true)
              }}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 8,
                border: 'none',
                background: 'transparent',
                padding: 0,
                cursor: 'pointer',
              }}
            >
              <span style={{ width: 12, height: 12, borderRadius: '50%', background: 'linear-gradient(135deg, #ef5d90, #f4a3bf)', boxShadow: '0 0 0 4px rgba(239,93,144,0.12)' }} />
              <span style={{ fontSize: '0.76rem', fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: accent }}>
                Unlock Path
              </span>
            </button>
          ) : (
            <div
              onMouseEnter={() => setUnlockHovering(true)}
              onMouseLeave={() => setUnlockHovering(false)}
              onPointerUp={handleUnlockPathPointerUp}
              style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}
            >
              <span style={{ width: 12, height: 12, borderRadius: '50%', background: 'linear-gradient(135deg, #ef5d90, #f4a3bf)', boxShadow: '0 0 0 4px rgba(239,93,144,0.12)' }} />
              <span style={{ fontSize: '0.76rem', fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: accent }}>
                Unlock Path
              </span>
              <button
                type="button"
                aria-label="Hide for now"
                title="Hide for now"
                onClick={hideUnlockPathForToday}
                style={{
                  width: 26,
                  height: 26,
                  borderRadius: 999,
                  border: '1px solid #f2c4d0',
                  background: 'rgba(255,255,255,0.9)',
                  color: '#b08090',
                  fontSize: '1rem',
                  fontWeight: 800,
                  cursor: 'pointer',
                  padding: 0,
                  lineHeight: 1,
                  opacity: (isMobile || unlockHovering) ? 1 : 0,
                  transition: 'opacity 180ms ease',
                  display: 'grid',
                  placeItems: 'center',
                }}
              >
                ×
              </button>
            </div>
          )}
        </div>

        {unlockCardVisible && displayedMilestone ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {latestUnlocked && latestUnlocked.day < displayedMilestone.day ? (
              <div
                style={{
                  background: '#fffafc',
                  border: '1.5px solid #ef7ea7',
                  borderRadius: 22,
                  padding: isMobile ? 14 : 18,
                  boxShadow: unlockCardState === 'unlock' ? '0 18px 34px rgba(232,64,122,0.16)' : '0 8px 18px rgba(232,64,122,0.04)',
                  transform: unlockCardState === 'unlock' ? 'scale(1.02)' : 'scale(1)',
                  transition: 'transform 220ms ease, box-shadow 220ms ease',
                }}
              >
                <div style={{ fontSize: '0.72rem', fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#e8407a', marginBottom: 8 }}>
                  {`Day ${latestUnlocked.day} - Unlocked`}
                </div>
                <div style={{ fontFamily: "'Playfair Display', serif", fontSize: isMobile ? '1.05rem' : '1.22rem', lineHeight: 1.2, color: '#3d1f2b', marginBottom: 8 }}>
                  {latestUnlocked.description}
                </div>
                <div style={{ fontSize: '0.82rem', color: '#7a5a65', lineHeight: 1.6, marginBottom: 14 }}>
                  {latestUnlocked.detail}
                </div>
                <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '0.4rem 0.75rem', borderRadius: 999, background: '#ef5d90', color: '#fff', fontSize: '0.75rem', fontWeight: 700 }}>
                  Active
                </div>
              </div>
            ) : null}

            <div
              style={{
                background: '#fffafc',
                border: '1.5px solid #ef7ea7',
                borderRadius: 22,
                padding: isMobile ? '14px 14px 12px' : '16px 16px 14px',
                opacity: unlockCardState === 'transition' ? 0 : 1,
                transform: unlockCardState === 'transition' ? 'translateY(8px)' : 'translateY(0)',
                transition: 'opacity 250ms ease, transform 320ms ease',
              }}
            >
              <div style={{ fontSize: '0.72rem', fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#e8407a', marginBottom: 8 }}>
                {displayedMilestone.day === 7 ? 'Day 7 — Week 1 Complete' : displayedMilestone.day === 14 ? 'Day 14 — Consistency Confirmed' : displayedMilestone.day === 30 ? 'Day 30 — One Month In' : displayedMilestone.day === 60 ? 'Day 60 — Depth Unlocked' : displayedMilestone.day === 90 ? 'Day 90 — Identity' : displayedMilestone.day === 120 ? 'Day 120 — Mastery' : `Day ${displayedMilestone.day}`}
              </div>

              <div style={{ fontFamily: "'Playfair Display', serif", fontSize: isMobile ? '1.05rem' : '1.22rem', lineHeight: 1.2, color: '#3d1f2b', marginBottom: 8 }}>
                {displayedMilestone.description}
              </div>

              <div style={{ fontSize: '0.82rem', color: '#7a5a65', lineHeight: 1.6, marginBottom: 14 }}>
                {displayedMilestone.detail}
              </div>

              {unlockNotice && milestoneActivated ? (
                <div style={{ fontSize: '0.75rem', color: '#e8407a', fontWeight: 700, marginBottom: 12 }}>
                  {unlockNotice}
                </div>
              ) : null}

              <div style={{ display: 'inline-flex', alignItems: 'center', padding: '0.36rem 0.7rem', borderRadius: 999, border: '1px solid #ef7ea7', color: '#e8407a', fontSize: '0.75rem', fontWeight: 700, marginBottom: 12 }}>
                {milestoneActivated ? 'Active' : `Next unlock - ${daysLeft} day${daysLeft === 1 ? '' : 's'} away`}
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <div style={{ flex: 1, height: 6, borderRadius: 999, background: '#f8d8e3', overflow: 'hidden' }}>
                  <div
                    style={{
                      width: `${progress * 100}%`,
                      height: '100%',
                      borderRadius: 999,
                      background: 'linear-gradient(90deg, #ef5d90, #f4a3bf)',
                      transition: 'width 600ms ease',
                    }}
                  />
                </div>
                <div style={{ fontSize: '0.75rem', color: '#8f6f7a', whiteSpace: 'nowrap' }}>
                  {progressPercent}% - {Math.min(progressStreak, displayedMilestone.day)} / {displayedMilestone.day} days
                </div>
              </div>
            </div>
          </div>
        ) : null}

        {showPhaseModal ? (
          <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'flex-end', justifyContent: 'center', zIndex: 500 }}>
            <div style={{ background: '#fff', borderRadius: '20px 20px 0 0', padding: '1.5rem', width: '100%', maxWidth: 480 }}>
              <p style={{ fontSize: '0.65rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: '#e8407a', marginBottom: 6 }}>Before you move forward</p>
              <p style={{ fontSize: '1rem', fontWeight: 700, color: '#3d1f2b', marginBottom: 8, fontFamily: 'Playfair Display, serif' }}>Complete your phase review first.</p>
              <p style={{ fontSize: '0.82rem', color: '#7a5a66', lineHeight: 1.6, marginBottom: 16 }}>Before moving into the next phase, Sage needs your quarterly review from this phase so the next one starts with the right clarity.</p>
              <button onClick={openQuarterlyReview} style={{ width: '100%', padding: '0.85rem', borderRadius: 12, border: 'none', background: 'linear-gradient(135deg, #e8407a, #f472a8)', color: '#fff', fontSize: '0.9rem', fontWeight: 700, cursor: 'pointer', marginBottom: 8 }}>Open phase review</button>
              <button onClick={() => setShowPhaseModal(false)} style={{ width: '100%', padding: '0.75rem', borderRadius: 12, border: '1.5px solid #f2c4d0', background: 'transparent', color: '#7a5a66', fontSize: '0.85rem', cursor: 'pointer' }}>I will do it later</button>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  )
}
